### ISSUE TITLE
global: specific mappings for each es major version

### ISSUE THREAD

**Issue by lnielsen** [inveniosoftware/invenio-search#114]
- [x] Add support for defining mappings per major ES version:

```
mappings/
mappings/v5/...
mappings/v6/...
```

- [x] Check if mapping incompatibility in ES is per major version
- [ ] ~Templates support~ (moved to #120)

**Comment by hjhsalo** [comment]
WRT _Check if mapping incompatibility in ES is per major version_ Elastic seems not to introduce any API breaking changes between minor versions. Breaking changes between minor versions affect things like the Java API, Packaging, Settings, etc (see, for example, https://www.elastic.co/guide/en/elasticsearch/reference/5.5/breaking-changes-5.2.html), so mappings and results are probably unaffected (the most "severe" change so far was [introducing stricter boolean values](https://www.elastic.co/guide/en/elasticsearch/reference/5.5/breaking-changes-5.2.html))  

API can (and probably will) break between major version, but for example some breaking changes from v2 to v5 Elastic introduced backwards compatibility: https://www.elastic.co/blog/strings-are-dead-long-live-strings (see section _Backwards compatibility_)
