### ISSUE TITLE
es5: specific templates for each ES major version

### ISSUE THREAD

**Issue by slint** [inveniosoftware/invenio-search#120]
Determine the structure and workings of how templates will be loaded for different major ES versions:

```
# For ES2
templates/record-stats
(or templates/v2/record-stats)

# For >ES2
templates/v5/record-stats
templates/v6/record-stats
...
```

(_This is partially addressed in #103_)

**Comment by lnielsen** [comment]
@slint was this not fixed for templates as well?

**Comment by slint** [comment]
Yup, it was split separately from the original issue, so it can be closed.

Closed via https://github.com/inveniosoftware/invenio-search/pull/103
