### ISSUE TITLE
tests: replace `sleep` with flush + refresh

### ISSUE THREAD

**Issue by slint** [inveniosoftware/invenio-search#125]
Many tests throughout Invenio tend to call `sleep(2)` after any Elasticsearch-related actions (indexing, deleting, creating indices, etc). This significantly affects total testing time and is non-deterministic, since in case of some Travis build/container slows down because of a memory swap or disk I/O throttling, these 2 seconds might not be enough, causing the build to fail.

Instead of that calling `current_search.flush_and_refresh(index_name)` is a valid alternative that programmatically guarantees that all Elasticsearch actions have been committed and written to disk.

**Comment by lnielsen** [comment]
Do you have some examples where it happens and weren't fixed yet. I've seen them as well, just don't remember where :-)

**Comment by lnielsen** [comment]
Closing. Please reopen if you find places where it's not fixed yet.
