### ISSUE TITLE
ext: Check for index existance before failing

### ISSUE THREAD

**Issue by ppanero** [inveniosoftware/invenio-search#147]
Currently when performing an ``invenio index init`` it throws an exception if one of the indeces already exists. 
```python
Traceback (most recent call last):
...
    raise HTTP_EXCEPTIONS.get(status_code, TransportError)(status_code, error_message, additional_info)
elasticsearch.exceptions.RequestError: TransportError(400, u'index_already_exists_exception', u'index [index-name/RL6Wt10rDe3sxw] already exists')
```

However, in my application I have to add indexes to the same application and I would like to do so by using the aforementioned command.

As far as I understand it would just be needed to check the existance of the mapping (and throw a warning if needed) in [put_templates](https://github.com/inveniosoftware/invenio-search/blob/master/invenio_search/ext.py#L268) or in [create](https://github.com/inveniosoftware/invenio-search/blob/master/invenio_search/ext.py#L239).

I can provide a PR if green light is given.
Cheers,
Pablo

**Comment by lnielsen** [comment]
Makes sense to me. Just take care of the semantics of the ``--force``.

**Comment by ppanero** [comment]
After some more testing it is not needed for my use case: Since new indexes will always go in a different alias, setting it as the search index works for invenio to see and create only the needed. However, I believe that if new ones are created in an old folder the error would happen, ``--force`` should do the job there.

From my side this can be closed, feel free to reopen if you consider it is needed and I'll work on it.
