### ISSUE TITLE
services: remove services from master

### ISSUE THREAD

**Issue by hachreak** [inveniosoftware/invenio-search#17]
#### Question

Are the services used or will be deprecated and substituted with something new?

I'm talking about: [services.py](https://github.com/inveniosoftware/invenio-search/blob/master/invenio_search/services.py) and all [services](https://github.com/inveniosoftware/invenio-search/tree/master/invenio_search/searchext/services).

##### Issues correlated:
- It depends from [knowledge](https://github.com/inveniosoftware/invenio-search/issues/13).
- Also the [Legacy removal](https://github.com/inveniosoftware/invenio/issues/3233) issue because most of the imports are from legacy code.

@jirikuncar @egabancho @kaplun @tiborsimko

**Comment by tiborsimko** [comment]
IIRC the only live use case is CDS... CC-ing also @ludmilamarian @kasioumis

**Comment by kaplun** [comment]
We don't use them in INSPIRE, but we plan to. However their current implementation is totally legacy dependent, so IMHO no point in preserving them. We can always re-implement them as needed, using new technology.

Of course for the CDS use case I let CDS team to speak.

**Comment by egabancho** [comment]
I agree with @kaplun, this is nice to have but it should be re-implemented using all the new goodies

**Comment by tiborsimko** [comment]
@hachreak please proceed with the implementation :)
