### ISSUE TITLE
api: "_all" not supported by ES7

### ISSUE THREAD

**Issue by ChiaraBi** [inveniosoftware/invenio-search#184]
`BaseRecordsSearch` is using `_all` as an index, but it has been deprecated in ElasticSearch 6 and removed in ElasticSearch 7. See the [ES7 breaking changes](https://www.elastic.co/guide/en/elasticsearch/reference/current/breaking-changes-7.0.html#all-meta-field-removed) for more info.

**Comment by slint** [comment]
I discussed this with @miltalex, and the solution probably will be to replace `_all` with `*`, since then prefixing will work as well

**Comment by miltalex** [comment]
In my instance is working fine 🙂

**Comment by ChiaraBi** [comment]
Yes, this is what I did in Zenodo as well to temporarily fix the problem. Should I make a PR here?
