### ISSUE TITLE
entrypoint changes for templates between version 3.1 and 3.2

### ISSUE THREAD

**Issue by rerowep** [inveniosoftware/invenio-search#193]
In the version vor invenio 3.2 we need a `__init__.py` file in the ES version directory for the register templates to function properly.  In version for 3.1 this was not necessary. This is not coherent with de definition of mappings.
There is also the question why I have to define a function in the `__init__.py` file which is responding the same as the already defined definition in the `setup.py` for example:
```
'invenio_search.templates': [
    'base-record = tests.es_templates:list_es_templates'
],
```
`__init__.py` in es_templates:
```
def list_es_templates():
    """Elasticsearch Templates path."""
    return [
        'tests.es_templates'
    ]
```

Solving of https://github.com/inveniosoftware/invenio-search/issues/171 would help a lot.

**Comment by lnielsen** [comment]
I'm not sure why it would have worked in v3.1 without the ``__init__.py`` file. It's documented in [v3.1](https://invenio.readthedocs.io/en/maint-3.1/tutorials/understanding-data-models.html#define-an-elasticsearch-mapping) that you need the ``__init__.py``.
