### ISSUE TITLE
SRU service implementation

### ISSUE THREAD

**Issue by rerowep** [inveniosoftware/invenio-search#210]
In 2014 there was a discussion about SRU service implementation here:
https://github.com/inveniosoftware/invenio/issues/1153
Some years later there are still no signs of an SRU implementation.
A lot of libraries heavily using this standard (http://www.loc.gov/standards/sru/)
for information retrieval from other libraries.
A system like invenio ILS https://invenio-software.org/products/ils/ would be
incomplete without SRU. Is it planned  to implement the SRU service into this 
module in the near futur?

Best regards

**Comment by lnielsen** [comment]
Sorry for the late reply. There's no plan to implement SRU for any of our services at this point. I'd be happy to advice in case you'd like to contribute it. Invenio-Search would not be the right module (provides backend support for Elasticsearch/OpenSearch) and SRU is a API endpoint, so it would fit best in a new module.
