### ISSUE TITLE
templates: slimmer facet UI

### ISSUE THREAD

**Issue by tiborsimko** [inveniosoftware/invenio-search#23]
Currently, the search results UI uses "fat" facets:

![2015-09-24-172251_2560x1440_scrot](https://cloud.githubusercontent.com/assets/517546/10077551/04b22f4e-62e1-11e5-8d4e-28d78e1c6a57.png)

The facets are "overdecorated", they occupy too much visible screen space, diluting attention of the user from the main page body.  Moreover, the user cannot see more one facet from the get-go, making navigation harder.

Usually, the facets are presented in a slimmer manner, see for example RERODOC:

![2015-09-24-172554_2560x1440_scrot](https://cloud.githubusercontent.com/assets/517546/10077635/764887b6-62e1-11e5-9708-3d2930135e0a.png)

This improves the UX and resembles more closely to what people are used to on the Internet (e.g. Amazon).

@drjova Can you please look at amending facet's CSS to make them slimmer by default?  CC-ing also @kaplun @jmartinm who were looking at facet usability on INSPIRE, and @nharraud who were improving facet mechanism in the past (https://github.com/inveniosoftware/invenio/pull/3400).

P.S. See also https://github.com/inveniosoftware/invenio/issues/3415 and other issues on this topic.

**Comment by kaplun** [comment]
Also to mention @eamonnmag's team work WRT [HepData](https://hepdata.net/search?q=) which is embracing a minimalist approach.

**Comment by egabancho** [comment]
In CDSLabs we have found another problem with them, simply they don't work.

It seems that there is some javascript that is not properly collected/built, this error in the console:
`Uncaught Error: undefined missing js/search/query_filters_widget`

**Comment by tiborsimko** [comment]
@eamonnmag @kaplun I like minimalist design too ("less is more!") however sometimes there are needs to select more than one item from the facet in order to perform an OR query, for example for alternative author names:

- Doe, J
- Doe, John

In the CERN Open Data use case, the live site testing showed that people wanted to have visible checkboxes, see https://github.com/cernopendata/opendata.cern.ch/issues/175.  Hence the current checkbox design...

**Comment by eamonnmag** [comment]
Yeah, this OR operation is on our todo. Here is a rough design I've been working on for the new INSPIRE that uses your approach @tiborsimko. It's more subtle but has the checkboxes.
![new-search-13](https://cloud.githubusercontent.com/assets/282396/10096060/d24c7bde-636e-11e5-93a6-048b917cd6fa.png)

**Comment by tiborsimko** [comment]
@eamonnmag Great, yes, that's the kind of setup I've been picturing for the checkboxes.
