### ISSUE TITLE
Better records' model_commited hook error message

### ISSUE THREAD

**Issue by nharraud** [inveniosoftware/invenio-search#35]
When `invenio_search.contrib.records:index_record_modification` fails because of a connection to elasticsearch issue, the error is reported on `invenio_records.api:create` as:
```
InvalidRequestError: This session is in 'committed' state; no further SQL can be emitted within this transaction.
```

We could log the reason of the rollback in order to make debug easier.

**Comment by tiborsimko** [comment]
(FWIW saw exactly this when debugging https://github.com/inveniosoftware/invenio-search/pull/34.)

**Comment by hachreak** [comment]
@nharraud we no longer have `invenio_search.contrib.records:index_record_modification`. 
Can we considered closed this issue?
