### ISSUE TITLE
api: stabilise and document

### ISSUE THREAD

**Issue by tiborsimko** [inveniosoftware/invenio-search#75]
- [x] check existing API functionality
    - [x]  Better records' model_commited hook error message #35 
- [x] add missing important API functionality
- [x] check API function signatures and parameters
- [x] enhance API docstrings (`param`, `returns`, `raises`, `versionadded`)
- [x] plug API functions to existing docs

**Comment by hachreak** [comment]
@jirikuncar @lnielsen do you think the first 3 points are fine? Or do we need to improve somehow the API?

**Comment by hachreak** [comment]
If there is no new Issues or PRs, I think we can close it together with #76 
WDYT @jirikuncar @lnielsen ?

**Comment by jirikuncar** [comment]
@hachreak we can close this one but not #76.
