### ISSUE TITLE
installation: support Elasticsearch 5.0

### ISSUE THREAD

**Issue by jirikuncar** [inveniosoftware/invenio-search#88]
We should have a look at supporting latest Elasticsearch 5.0 and unpin elasticsearch dependency created in #87.

Update `.travis.yml` configuration (see #58).

NOTE: we might need to wait for release of Elasticsearch-DSL supporting Elastic 5.0.

**Comment by nharraud** [comment]
@jirikuncar elasticsearch-dsl [just released a version requiring elasticsearch>=5.0.0](https://github.com/elastic/elasticsearch-dsl-py/commit/4622a2661c1406ffc4016c53c907bd8caef0e68f)

**Comment by nharraud** [comment]
This in fact breaks new builds as elasticsearch-dsl asks for `'elasticsearch>=5.0.0,<6.0.0'` and invenio-search asks for `'elasticsearch>=2.0.0,<3.0.0'`

**Comment by nharraud** [comment]
Ah wait. The change might impact the services currently running Invenio 3.
The docs says:
```
For Elasticsearch 2.0 and later, use the major version 2 (2.x.y) of the library.

For Elasticsearch 1.0 and later, use the major version 0 (0.x.y) of the library.
```
Thus it is not just a matter of supporting Elasticsearch 5.0 but also a matter of stopping the support for Elasticsearch 2.0.
Is everybody ok to move to elasticsearch 5 right away? I don't think that there is a problem for B2Share.

**Comment by nharraud** [comment]
After discussing with @egabanch, @PXke and @krzysztof I suggest to leave the the elasticsearch and elasticsearch-dsl libs unpinned and let the overlay decide which version they want to use.

The cons of this option is that our build will break each time elasticsearch release a new version of one of the libs without releasing the other.
