### ISSUE TITLE
search: elasticsearch-dsl 5.1.0 changes Response constructor signature

### ISSUE THREAD

**Issue by diegodelemos** [inveniosoftware/invenio-search#96]
https://github.com/elastic/elasticsearch-dsl-py/commit/0d1be428ad0f93a96f6b471454bc4085c1905f9a

We can pin `elasticsearch-dsl<5.1.0` for now in order to pass tests on travis

**Comment by nharraud** [comment]
Fixed by #118 [here](https://github.com/inveniosoftware/invenio-search/pull/118/files#diff-0bec294943ab05411ef28254d696d7ddR120)
